### ISSUE TITLE
Add Swisspeddose Chapter

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#1]
Name of chapter: **Swisspeddose**
Style of Table extracted from XML:

**The data of below table does not yet seem to be available in the XML.**

![swisspeddose](https://user-images.githubusercontent.com/4953/51614535-23b82600-1f26-11e9-8d65-7c3ab040066d.png)

Use the following ATC Code: J05AB01
`Aciclovir (IV)
ATC-Code: J05AB01
Indication: Herpes zoster (immunocompromised patients)`
you will find `<CaseID>137</CaseID>` for two dosage recommendations. Then apply above table view in the FI.

**Comment by zdavatz** [comment]
https://swisspeddose.ch

**Comment by bettar** [comment]
How do you relate the sections `<CodeType>ROA</CodeType>` to anything else ?

**Comment by bettar** [comment]
ATC J05AB01 has a matching pair of Code and Case:

  `<Code><CodeValue>J05AB01</CodeValue>`
  `<Case><ATCCode>J05AB01</ATCCode>`

ATC N02BA01 does not have a matching Case:

  `<Code><CodeValue>N02BA01</CodeValue>`

**Comment by zdavatz** [comment]
wait for the next XML Release.

**Comment by bettar** [comment]
There are 64 ATC codes in `Cases`
There are 5059 ATC codes in `Codes`

The Description is in `Codes` but the keys and IDs to connect all the information are in `Cases` so we can create only 64 tables that have a description

**Comment by zdavatz** [comment]
ok, good to know! Please put that in the report.

**Comment by zdavatz** [comment]
1. remove extra carriage return.
<img width="450" alt="bildschirmfoto 2019-02-22 um 20 16 22" src="https://user-images.githubusercontent.com/4953/53265654-133ecb00-36df-11e9-996f-fafe19441f50.png">

2. And change the “to” into a “-“ in _Age_ and _Weight_

3. remove _x daily_ in column _Daily repetitions_

**Comment by bettar** [comment]
How about translating "Indication" as well ?

**Comment by zdavatz** [comment]
DE: Indikation
FR: Indication

**Comment by zdavatz** [comment]
EN: Remark
DE: Bemerkung
FR: Remarque

**Comment by zdavatz** [comment]
Remove Columns if they only contain zeros.

**Comment by zdavatz** [comment]
If column "Tägliche Wiederholungen" contains zeros, then skip it.
