### ISSUE TITLE
Generate a Report HTML file

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#10]
Generate a report HTML file with the name `amiko_owner_report_de.html` where all the output information is placed when using `--verbose` option.

See http://pillbox.oddb.org/amiko_owner_report_de.html for the daily sample file of the Java-DB.

**Comment by bettar** [comment]
I guess you want the file name to end ind `_fr` instead of `_de` if we generate the French version of the db file.

**Comment by zdavatz** [comment]
yes please.

**Comment by zdavatz** [comment]
looking good!
