### ISSUE TITLE
Something seems to have changed in the new Swissmedic File

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#100]
running 

`./pharma --inDir ../input`

results in

Reading swissmedic XLSX
terminate called after throwing an instance of 'xlnt::exception'
  what():  xlnt::exception : unknown country code: 10485

**Comment by bettar** [comment]
One difference is that the date format changed from "dd.mm.yyyy" to "mm.dd.yyyy", but there is more to it. Still investigating...

**Comment by zdavatz** [comment]
https://github.com/tfussell/xlnt/blob/master/docs/advanced/Formatting.md

**Comment by zdavatz** [comment]
https://github.com/tfussell/xlnt/blob/master/docs/introduction/Features.md

**Comment by zdavatz** [comment]
Microsoft Office gives me this: `[$-sah-RU,1]TT.MM.JJJJ;@`

**Comment by bettar** [comment]
The actual code string as parsed by XLNT is 10485 which is assumed to be a 17-bit hexadecimal number 0x10485 (decimal 66693). Maybe LibreOffice expects a 16-bit number so it masks off the leading 1, keeping just 0x0485, then it ignores the unimportant leading 0 and it shows "485".

**Comment by zdavatz** [comment]
Temporary fix for Issue #100. Insert line 66 like in the screenshot. This is not the "proper" way of fixing the problem, and it should be NOT be a pull request to the XLNT project. The correct way of fixing the problem is already outlined above.

![Screenshot 2019-09-06 at 14 25 08](https://user-images.githubusercontent.com/4953/64429249-d86a1680-d0b5-11e9-9f09-f545e304eca2.png)

**Comment by zdavatz** [comment]
works great!

**Comment by zdavatz** [comment]
[swissmedic.patch.txt](https://github.com/zdavatz/cpp2sqlite/files/3584890/swissmedic.patch.txt)

**Comment by zdavatz** [comment]
https://github.com/tfussell/xlnt/pull/409
