### ISSUE TITLE
if the Pharmacode is bigger then 7900000, skip the product.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#104]
pharmacodes in column A of `Artikelstamm_Vollstamm.csv` that are larger then 7900000 should not be in the dbs 
* rose_db_full.db
* rose_db_atc_only.db

**Comment by bettar** [comment]
There are Pharma codes (larger than 7900000) also in column O. What shall we do about them ?

**Comment by bettar** [comment]
About 20 lines don't even have a numerical value in column A.What shall we do about them ?

**Comment by zdavatz** [comment]
Report them in the Reportfile.

**Comment by zdavatz** [comment]
> About 20 lines don't even have a numerical value in column A.What shall we do about them ?

Report them in the Reportfile.

**Comment by zdavatz** [comment]
> There are Pharma codes (larger than 7900000) also in column O. What shall we do about them ?

For the moment leave them as  they are.

**Comment by zdavatz** [comment]
This error still happens `voll.cpp:202 Error stoi`

**Comment by bettar** [comment]
You are asking to skip lines with pharmacode > 7900000. By looking at the CSV file it looks like we should skip lines with pharmacode >= 7900000 instead
