### ISSUE TITLE
add Biotechnologika to full_db and atc_db

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#108]
append Biotechnologika Flag from (Column E) from [Swissmedic.xlsx](https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_human.xlsx.download.xlsx/zugelassene_packungen_ham.xlsx) to `full_db` and `atc_db` in column `flags`.

Flag name has to be `BioT`

**Comment by bettar** [comment]
When you say `full_db` I guess you mean `rose_db_full.db` not `amiko_db_full_idx_de.db`.

**Comment by zdavatz** [comment]
> When you say `full_db` I guess you mean `rose_db_full.db` not `amiko_db_full_idx_de.db`.

yes, correct.

**Comment by zdavatz** [comment]
`, BioT` remove the `,` if there is only the `BioT` in the flags folumn.
