### ISSUE TITLE
Spurious chapter name

### ISSUE THREAD

**Issue by bettar** [zdavatz/cpp2sqlite#11]
For regnr 53985 the product name is `ACC Sandoz® Brausetabletten; ACC Sandoz® Granulat` which contains a semicolon. This semicolon is mistakenly interpreted as a chapter name separator.
This has been observed in AmiKo with the Java database. AmiKo doesn't crash, but the chapter links are offset by one.

**Comment by bettar** [comment]
This also applies to rn 51075 Calciumfolinat, and rn 62980 Clindamycin and a few others.

**Comment by bettar** [comment]
rn 61492 Co-Candesartan Sandoz has three of those spurious section names !

**Comment by zdavatz** [comment]
So how can we work around this? iOS does not crash with the Java DB.

**Comment by zdavatz** [comment]
replace `;` with a normal "bullet".

**Comment by zdavatz** [comment]
a test link: http://www.swissmedicinfo.ch/ShowText.aspx?textType=FI&lang=de&authNr=53985

**Comment by zdavatz** [comment]
use a thinner bullet.  5cba265c66eff4144c24c4aa88419ddf
