### ISSUE TITLE
Kunden_alle_NEU.csv is now automatically being generated

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#111]
`Kunden_alle_NEU.csv` is being automatically generated. Seems to cause some errors.

**Comment by bettar** [comment]
Please provide more details on how to reproduce "some errors"

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/70898636-4f884280-1ff5-11ea-8af3-b5506e836daf.jpeg)

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/70898684-69298a00-1ff5-11ea-9779-3eef565c14b5.jpeg)
