### ISSUE TITLE
add "test" option to zR download

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#112]
if the "test" option is given on the command-line, then the files from the Test Dir are being downloaded. If the "test" option is omitted, then the files of the regular dir are download. See aips2sqlite as reference.

**Comment by bettar** [comment]
Command line for which command ? Maybe `download_zr.sh` ?

**Comment by bettar** [comment]
`download_zr.sh` already has an optional parameter to specify the parent directory of `downloads` and `output`. Do you want both optional parameters ?

**Comment by zdavatz** [comment]
Yes for `download_zr.sh`. I am now dong `download_zr.sh test` I guess that should work.
