### ISSUE TITLE
running build.sh on a new Server results in refdata.cpp:112, Error No such node (ARTICLE)

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#113]
running `build.sh` on a new Server results in `refdata.cpp:112, Error No such node (ARTICLE)`. `refdata_pharma.xml` file is 0 Bytes of size. Seems something with the download is strange. This only happens on the new server. Must be related to the download changes. Build options are:

```
STEP_DOWNLOAD_PUBLIC=true
STEP_RUN_C2S=true
```

**Comment by bettar** [comment]
I cannot reproduce the problem, but in my case the size of `refdata_pharma.xml` is the expected 22 MB.

**Comment by zdavatz** [comment]
Ok. Let me test again.
