### ISSUE TITLE
remove Swisspeddose remarks for Fungizone

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#119]
The ATC-Code `J02AA01` goes for two products: `AmBisome` and `Fungizone`. The Swisspeddose remarks should only be shown for `AmBisome`. Use the 5 digit Swissmedic Number from this file https://github.com/zdavatz/cpp2sqlite/blob/master/input/swisspeddose_blacklist.txt to to decide for which products not to show the swisspeddose tables.

![latest-screenshot](https://user-images.githubusercontent.com/4953/75332123-25b88b00-5884-11ea-925e-a4b4ba2f1652.png)
![latest-screenshot](https://user-images.githubusercontent.com/4953/75332143-2f41f300-5884-11ea-8d36-b9156042f5e6.png)

**Comment by b123400** [comment]
Sorry, what is "The Swisspeddose remarks", and which output file should I filter?

**Comment by zdavatz** [comment]
Dieses Script 
```
cd /usr/local/src/cpp2sqlite/scripts
source ./steps_public1.source
source ./steps_public2.source
./download.sh
cd /usr/local/src/cpp2sqlite/build
time ./cpp2sqlite --verbose --lang=fr --inDir ../input
time ./cpp2sqlite --verbose --inDir ../input
```
generiert die folgenden Files: `amiko_db_full_idx_de.db` und `amiko_db_full_idx_fr.db`

`./download.sh` ladet auch diese Datei runter: `swisspeddosepublication.xml`darin sind die Kinderdosierungen enthalten. Die Kinderdosierungen werden via dem 7-stelligen ATC-Code in die Fachinfo geschrieben, falls die Fachinfo den gleichen ATC-Code hat. Für 5-stellige Swissmedic Codes im File https://github.com/zdavatz/cpp2sqlite/blob/master/input/swisspeddose_blacklist.txt dürfen keine Swisspeddose Tabellen in die Fachinfo geschrieben werden. Die Zeilen, welche mit `#` beginnen, kannst Du ignorieren.
