### ISSUE TITLE
Make source steps_public2.source ./download.sh more failsafe

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#126]
currently if the the following steps delivers a file that is corrupted or to small the resulting databases will not work
```
#!/bin/bash
cd /usr/local/src/cpp2sqlite/scripts
source steps_public2.source
./download.sh

```
I suggest we save the file size of the current download in a separate text file so when we initiate a new download then we compare the new file size to the one in the text file. If the difference is bigger than 30% we do not overwrite the old downloaded the file.

**Comment by zdavatz** [comment]
after a discussion with @bettar we decided to check the validity with xlnt to see if the XLSX is valid or not.

**Comment by bettar** [comment]
An xlsx file is actually a ZIP file so the integrity can be conveniently checked with
`unzip -t file.xlsx`

**Comment by zdavatz** [comment]
Ok, please update the script.

**Comment by zdavatz** [comment]
1. If it is the first download abort if the file is not a valid zip file.
2. If the file is already there and the verification fails use the old file.
