### ISSUE TITLE
genereate rose_ids.json based on Kunden_alle_NEU.csv

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#128]
Make sure that the amount of lines match. `Kunden_alle.csv` does not have to be downloaded anymore.

**Comment by bettar** [comment]
Do you want also rose_conditions.json to be generated from Kunden_alle_NEW.csv ?

**Comment by zdavatz** [comment]
yes.

**Comment by zdavatz** [comment]
no.
