### ISSUE TITLE
Introduce timeout with wget for swissmedic.ch

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#129]
1. If the file size did not change, do not overwrite the old file.
2. If Swissmedic [does not respond](https://stackoverflow.com/questions/43662591/wget-using-timeout-and-tries-together/43664731), then fall back to old file.

**Comment by zdavatz** [comment]
seems like the name is not being moved back:
```
-rw-r--r-- 1 zdavatz zdavatz  2949903 Jul  3 16:40 zugelassene_packungen_ham.xlsx
-rw-r--r-- 1 zdavatz zdavatz        0 Jul 20 20:40 swissmedic_packages.xlsx
```

**Comment by zdavatz** [comment]
https://gist.github.com/hrwgc/7455343

**Comment by bettar** [comment]
$ wget -S --spider https://www.swissmedic.ch

**Comment by zdavatz** [comment]
```
zdavatz@MacBookPro:~$ wget -S --spider https://www.swissmedic.ch
Spider-Modus eingeschaltet. Es wird geprüft, ob die Datei auf dem Server existiert.
--2020-07-21 11:03:34--  https://www.swissmedic.ch/
Auflösen des Hostnamens www.swissmedic.ch (www.swissmedic.ch)… 162.23.129.86
Verbindungsaufbau zu www.swissmedic.ch (www.swissmedic.ch)|162.23.129.86|:443 … verbunden.
Es ist nicht möglich, eine SSL-Verbindung herzustellen.
```

**Comment by bettar** [comment]
Spider mode enabled. Check if remote file exists.
--2020-07-21 10:02:52--  https://www.swissmedic.ch/
Resolving www.swissmedic.ch (www.swissmedic.ch)... 162.23.129.86
Connecting to www.swissmedic.ch (www.swissmedic.ch)|162.23.129.86|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
