### ISSUE TITLE
Check swisspeddose file for ATC Code description as Fallback solution.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#13]
[1] no text for ATC: <R03AK08> (first rn: 66747) - There is a text for this ATC-Code in swisspeddose in German and French.

**Comment by bettar** [comment]
Before the fallback they were already all found in etc file

  ATC text found: 4292, not found: 0

Now there is a fallback, but it's never taken

  ATC text found: 4292, found in peddose: 0, not found: 0
