### ISSUE TITLE
sqlite file only shows 42 lines

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#130]
sqlite file only shows 42 lines. But the size of the files is ok. Also aips2sqlite generates a correct file.

http://pillbox.oddb.org/amiko_db_full_idx_de.zip

**Comment by bettar** [comment]
The corresponding report files is also truncated: the "Usage" section is missing

**Comment by bettar** [comment]
The French DB file has the same problem (38 lines)

**Comment by bettar** [comment]
cpp2sqlite receives a segmentation fault at 64% progress in the generation of the DB file

**Comment by bettar** [comment]
The problem was in file peddose.cpp function getHtmlByAtc() for ATC J01CE02, caseID 175 which has 0 dosages and the code was trying to use the 1st dosage

**Comment by zdavatz** [comment]
Mille Grazie!
