### ISSUE TITLE
Do not skip Fachinfos that do not have any GTIN or are not in the swissmedic packages file.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#138]
It can happen, that the AIPS XML will publish a Fachinfo with the 5 digit Swissmedic registration number but the 5 digit Swissmedic registration number can not be found in `zugelassene_packungen_ham.xlsx`. In this case the Fachinfo should still be added to the sqlite database even if it does not contain any packages yet.

This happend with `Amlodipin Valsartan Sandoz`

76 80 66015 010 4

76: Schweiz
80: Swissmedic
5-stellige Swissmedic-Nummer: 66015 (column A for `zugelassene_packungen_ham.xlsx` and `Erweiterte_Arzneimittelliste HAM.xlsx`)
3-stellige Packungsnummer: 010 (column K for `zugelassene_packungen_ham.xlsx`)
Prüfziffer: 4

It can also happen, that the product is already in the Refdatabase but not yet in the [Swissmedic Packages file](https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_human.xlsx.download.xlsx/zugelassene_packungen_ham.xlsx).

So ergo put all the Fachinfos into the sqlitedb even if they are still missing the packages from `zugelassene_packungen_ham.xlsx`

The [java version](https://github.com/zdavatz/aips2sqlite) does exactly that.

**Comment by zdavatz** [comment]
another nice sample for this issue is `Comirnaty`. The product is found in [amiko.zurrose.ch](https://amiko.zurrose.ch/de/fi/gtin/68225) (DB generated with aips2sqlite) the product is not found in amiko.oddb.org (db generated with cpp2sqlite).

**Comment by b123400** [comment]
Es gibt `Erweiterte_Arzneimittelliste HAM.xlsx` und `zugelassene_packungen_ham.xlsx`.
Was ist die Untershied?

Sie sagen dass, die AIPS XML Datei hat 66015, aber ich kann nicht das finden.
Allerdings, ich kann von `zugelassene_packungen_ham.xlsx` 66015 finden.

**Comment by b123400** [comment]
Ich denke dass, Sie meinen, wenn etwas ist in `zugelassene_packungen_ham.xlsx`, aber nicht in die AIPS XML Datei, wir sollen es zu Sqlite hinzufügen.

**Comment by zdavatz** [comment]
Yes, every Fachinfo has one or more 5 digit Swissmedic numbers. If that number is not yet in `zugelassene_packungen_ham.xlsx` or in `refdata_pharma.xml` you can still add the Fachinfo to the sqlitedb without adding any package information (GTIN).

**Comment by zdavatz** [comment]
`Erweiterte_Arzneimittelliste HAM.xlsx` does not cotain any information about packages. It does not contain any package numbers. It only contains 5 digit Swissmedic Numbers (column A) and the Sequence number (column B). 

Additionally to column A and B `zugelassene_packungen_ham.xlsx` also contains the package number (column K).

**Comment by zdavatz** [comment]
The 5 digit Swissmedic Number is in the aips.xml, see: 

![66015](https://user-images.githubusercontent.com/4953/103795785-b3d5d400-5046-11eb-894c-eaf9102387ae.png)

**Comment by zdavatz** [comment]
> Ich denke dass, Sie meinen, wenn etwas ist in `zugelassene_packungen_ham.xlsx`, aber nicht in die AIPS XML Datei, wir sollen es zu Sqlite hinzufügen.

Das Gegenteil. 

The reason for this is, that some pharmaceutical companies decide first publish the Fachinfo, where as the file with the package information zugelassene_packungen_ham.xlsx (column K) is only published once a month, at the beginning of every month. The aips.xml is published every day. So in order to start marketing the prodcut, the pharmaceutical company first just publishes the Fachinfo in the aips.xml.

**Comment by zdavatz** [comment]
In the daily report file http://pillbox.oddb.org/amiko_report_de.html in the chapter `aips REGNRS (found/not found)` we already count the opposite: "not found anywhere: 94" this means registrations number that have no Fachinfo. 

What we are looking for is the opposite: Fachinfos that have a registration number that are not yet found `zugelassene_packungen_ham.xlsx` or Fachinfos that have no registration number at all yet.

**Comment by zdavatz** [comment]
I will close this issue, till the problem shows up again. Maybe with the vaccination for Moderna.

**Comment by zdavatz** [comment]
> Sie sagen dass, die AIPS XML Datei hat 66015, aber ich kann nicht das finden.

How did you search for `66015` in AIPS.xml?

**Comment by b123400** [comment]
I opened the file with `vim aips.xml`, and then typed `/66015`.
Vim says: E486 Pattern not found: 66015

**Comment by zdavatz** [comment]
Probably you have to escape some characters. The number is there, because it is in http://pillbox.oddb.org/amiko_db_full_idx_zr_de.zip ;)
