### ISSUE TITLE
add Chargenrückrufe, DHCP, HPC News, Drugshortage to Fachinfo in DE an FR

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#140]
running [ymeteor](https://github.com/zdavatz/ymeteor) with the following options 
```
meteor --once --settings swissmedic.json
meteor --settings drugshortage.json --once
```
generates the following JSON files in `ymeteor/public/exports`

1. chargenrueckrufe_de.json
2. dhcp_hcp_de.json
3. chargenrueckrufe_fr.json
4. dhcp_hcp_fr.json
5. drugshortage.json

the information of these JSON files has to be parsed by cpp2sqlite added to the Fachinfo (currently if swisspeddose and sappinfo exist, are added to the Fachinfo in the end). Chargenrückrufe, DHCP/HPC and Drugshortage Information has to be added in the same manner, if they exist. You can use the 5 digit Swissmedic Number for matching with the Fachinfos. The 5 digit Swissmedic number is in the JSON files.

![chapter_batch_dhcp_hpc_chargen](https://user-images.githubusercontent.com/4953/103901826-f1e00000-50f9-11eb-8789-76a142c4e525.png)

Chargenrückrufe = Retraits de lots (FR)
DHCP/HPC = DHCP/HPC (FR)
Drugshortage = Drugshortge (FR)

**Comment by zdavatz** [comment]
Important: Make a separate module for `Drugshortage` and one for `DHCP/HPC/Chargenrückrufe`. Currently we have the following modules

1. cpp2sqlite  
2. interaction  
3. pharma  
4. sappinfo  
5. zurrose

so then we will have two more:

* drugshortage
* dhcphpcbatchrecalls

**Comment by zdavatz** [comment]
For Drugshortage lets add them in the chapter "Packungen" if the GTIN is in the Drugshortage.json file.

![drugshortage](https://user-images.githubusercontent.com/4953/103900791-86496300-50f8-11eb-8894-51b4bcd404fc.png)

**Comment by b123400** [comment]
Why should we add 2 more modules?

The entire sqlite database (amiko_db_full_idx_[de|fr].db) is generated by `cpp2sqlite`, I think it is not designed to create the same database with 3 different modules.
I think it will be more straight forward to implement it in `cpp2sqlite`

**Comment by zdavatz** [comment]
sappinfo is also a separate module. The point for the new modules is that if something breaks then it does not affect the Fachinfo.

**Comment by zdavatz** [comment]
1. If you can not find the field "erste Meldung" in `drugshortage.json` just skip it for the moment and do not add it. I have to check with @hamzamu about the ymeteor parsing.
2. If the GTIN is not drugshortage.json do **not** add `Drugshortage` to the chapter name.

**Comment by b123400** [comment]
There is something like this in the JSON:

```
"tageSeitErsterMeldung": 678,
```

but it is not a date string like "11.01.2021"

**Comment by zdavatz** [comment]
> There is something like this in the JSON:
> 
> ```
> "tageSeitErsterMeldung": 678,
> ```
> 
> but it is not a date string like "11.01.2021"

I guess we would have to calculate the date string.
