### ISSUE TITLE
Add a title to the Report file and link it with the github repo link.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#18]
~~1. Rename the report file to: amiko_report_de.html (de for German, fr for French).~~
2. Add a title to the Report file: This Report was generated by: cpp2sqlite.
3. Link _cpp2sqlite_ with https://github.com/zdavatz/cpp2sqlite/

**Comment by zdavatz** [comment]
done with: 59b4211fa9181b85a3459134882

**Comment by bettar** [comment]
A title in the HTML body or a `<title>` in the HTML code, or both ?

**Comment by zdavatz** [comment]
In the HTML Body at the top of the HTML page and in the title Tag: 
This Report was generated by: cpp2sqlite.

**Comment by zdavatz** [comment]
nice!
