### ISSUE TITLE
DHPC/HPC and Chargenrückrufe Links throw an error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#180]
1. Search for "DHPC"
2. Klick an entry
3. Klick the PDF link. 
4. The following error comes:
5. ![latest-screenshot](https://user-images.githubusercontent.com/4953/107801318-33e70c00-6d60-11eb-9a6f-20fffbab0b40.png)
6. It seems that the URL is not parsed correctly. The browser shows ![latest-screenshot](https://user-images.githubusercontent.com/4953/107801392-4e20ea00-6d60-11eb-9e59-5e6dc37a83b8.png)
7. Above error happens on AmiKo-Web.
8. On AmiKo for iOS nothing happens if you click the link.
9. It seems that the **wrong domain** is taken.
10. `https://amiko.zurrose.ch/dam/swissmedic/de/dokumente/marktueberwachung/chargenrueckruf/chargenrueckruf-kadcyla-pulver.pdf.download.pdf/20201230_Kadcyla_DHPC_DE_Final_20201228.pdf` 
11. should actually be
12. `https://swissmedic.ch/dam/swissmedic/de/dokumente/marktueberwachung/chargenrueckruf/chargenrueckruf-kadcyla-pulver.pdf.download.pdf/20201230_Kadcyla_DHPC_DE_Final_20201228.pdf`

**Comment by b123400** [comment]
This should be fixed in https://github.com/zdavatz/ts4cpp/commit/51957bcc22c3149cb52c7c00b530e632b89b7e75
