### ISSUE TITLE
Convert SAI XML to sqlitedb

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#181]
1. Implement an additional module `./sai`
2. If this module is run, then 
3. Dowload the latest file from https://sai.refdata.ch/download
4. Convert all XML data to an sqlitedb with the file name `sai.db` and `sai.db.zip`
5. XSD Files are here: https://sai.refdata.ch/download/schemazip
6. Each line of the sqlitedb has to be a Package, a 13 digit GTIN, XML Tag name is `GTIN_INDUSTRY`.
7. Each `Packung` Sub Tag in the file `Typ1-Packungen.XML` is a separate column, sample
```
    <ZULASSUNGSNUMMER>56775</ZULASSUNGSNUMMER>
    <SEQUENZNUMMER>1</SEQUENZNUMMER>
    <PACKUNGSCODE>2</PACKUNGSCODE>
    <ZULASSUNGSSTATUS>D</ZULASSUNGSSTATUS>
    <BEMERKUNG_FREITEXT>Tube applicateur</BEMERKUNG_FREITEXT>
    <PACKUNGSGROESSE>5</PACKUNGSGROESSE>
    <PACKUNGSEINHEIT>G</PACKUNGSEINHEIT>
    <WIDERRUF_VERZICHT_DATUM>2010-09-27</WIDERRUF_VERZICHT_DATUM>
    <BTM_CODE/>
    <GTIN_INDUSTRY>7680567750025</GTIN_INDUSTRY>
    <IM_HANDEL_DATUM_INDUSTRY/>
    <AUSSER_HANDEL_DATUM_INDUSTRY>2010-09-27</AUSSER_HANDEL_DATUM_INDUSTRY>
    <BESCHREIBUNG_DE_REFDATA>GYNAZOL 1 Vag Cr 5 g</BESCHREIBUNG_DE_REFDATA>
    <BESCHREIBUNG_FR_REFDATA>GYNAZOLE 1 cr vag 5 g</BESCHREIBUNG_FR_REFDATA>
```
8. `Typ1-Praeparate.XML` Information has to be assigned to the `Typ1-Packungen.XML` in separate column.
9. `Typ1-Sequenzen.XML` Information has to be assigned to the `Typ1-Packungen.XML` in separate column.
10. `Typ1-Stoff-Synonyme.XML` Information has to be assigned to the `Typ1-Packungen.XML` in separate column.
11. `Typ1-Deklarationen.XML`Information has to be assigned to the `Typ1-Packungen.XML` in separate column. Certain "Packungen" may have many active agents (each active agent has a unique Hash). All active agents have to be in one cell, including the dosage and galenic form. Use `;` as separator. Always start with the lowest `<ZEILENNUMMER> </ZEILENNUMMER>`, `<SORTIERUNG_ZEILENNUMMER>1</SORTIERUNG_ZEILENNUMMER>` first. Sortorder is ascending.
12. Report all line where `<GTIN_INDUSTRY/>` is empty. Report the line by content of the Tag `<ZULASSUNGSNUMMER>` and the file.

**Comment by b123400** [comment]
Müssen die Wirkstoffe in eine Zelle? Es gibt viel Wirkstoffe, z.B, es gibt 64 Wirkstoffe für zulassungsnummber = 68168. Ich denke es ist besser, falls wir nach andere Tabelle ihnen stellen. z.B.

## Tabelle Packgunen

| id | zulassungsnummber | gtin ..... |
| --| ----------------------|--------|
| 1  | 68168                         |   ...        | 
| 2  | ...                                |   ...        | 

## Tabelle Deklaration

| id | stoff_id  | zulassungsnummber | ..... |
| --| ---------|----------------------|---|
| 1  | hash1 | 68168                         |    | 
| 2  | hash2 | 68168                         |    | 

Was denken Sie?

**Comment by zdavatz** [comment]
The active agents (Wirkstoffe) have to go into the same cell, but not the same line. Every active agent is a new line in the same cell. The title of the column is `Zusammensetzung`:
```
1. STOFFSYNONYM; SYNONYM_CODE; MENGE; MENGEN_EINHEIT; DEKLARATIONSART; STOFFKATEGORIE;
2. STOFFSYNONYM; SYNONYM_CODE; MENGE; MENGEN_EINHEIT; DEKLARATIONSART; STOFFKATEGORIE;
3. STOFFSYNONYM; SYNONYM_CODE; MENGE; MENGEN_EINHEIT; DEKLARATIONSART; STOFFKATEGORIE;
...
```

**Comment by zdavatz** [comment]
We are doing something similar in the current sqlitedb: 
![latest-screenshot](https://user-images.githubusercontent.com/4953/118442901-7e737e00-b6eb-11eb-9620-6e2bbd0cf794.png)
