### ISSUE TITLE
add line number in first column of `sai.db`

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#185]
1. add line number in first column of `sai.db`
2. So if you sort by a column you can still see the line number.

**Comment by b123400** [comment]
There is a `_id` column, is this ok?

![sai db 2021-05-18 20-57-40](https://user-images.githubusercontent.com/127193/118646870-b4b01b00-b81b-11eb-80e4-a72729294f57.png)

**Comment by zdavatz** [comment]
Perfekt! Thank you!
