### ISSUE TITLE
French Version still has some Sub-Tag problems

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#21]
<img width="796" alt="bildschirmfoto 2019-02-28 um 19 53 54" src="https://user-images.githubusercontent.com/4953/53590964-3e1f9800-3b93-11e9-899d-67d82088bb37.png">
<img width="624" alt="bildschirmfoto 2019-02-28 um 19 55 08" src="https://user-images.githubusercontent.com/4953/53590966-3e1f9800-3b93-11e9-9136-dcd532570c32.png">

**Comment by bettar** [comment]
The problem in the second image (FDG_FR) also appears in the German version
