### ISSUE TITLE
50974 French/German Version Footer is strange

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#22]
Reg# 50974 - same problem in DE DB.
<img width="995" alt="bildschirmfoto 2019-02-28 um 19 56 19" src="https://user-images.githubusercontent.com/4953/53590852-fd278380-3b92-11e9-945b-2b2e5904d715.png">

**Comment by bettar** [comment]
Please explain why it is "strange"

**Comment by zdavatz** [comment]
<img width="814" alt="bildschirmfoto 2019-03-01 um 15 16 03" src="https://user-images.githubusercontent.com/4953/53643676-f3eef300-3c34-11e9-8dc0-71bde7ea0da8.png">

**Comment by bettar** [comment]
This problem applies to all fachinfos with XML of the "second" type

**Comment by zdavatz** [comment]
ok, good to know.
