### ISSUE TITLE
Create Bash-Script to download all the files.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#3]
1. Bash-Script also has to create a _downloads_ dir where all the downloaded files go.
2. Bash-Script also also to create a _output_ dir where all the outputted files go.

Swissmedic: https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_ham.xlsx.download.xlsx/Zugelassene_Packungen%20HAM_31012019.xlsx

**Comment by zdavatz** [comment]
1. You run: _cpp2sqlite --verbose_
2. Will download all the files.
3. Will create _output_ and _downloads_ dir.
4. Will generate the report and the German DB.

**Comment by bettar** [comment]
Is there a list of the files to be downloaded and relative URLs ?

**Comment by zdavatz** [comment]
AIPS: http://download.swissmedicinfo.ch
Refdata: see java code.

**Comment by zdavatz** [comment]
swisspeddose: https://db.swisspeddose.ch/app/uploads/xml_publication/swisspeddosepublication-2019-02-21.xml

**Comment by bettar** [comment]
Outline of file AllDown.java
![screenshot 2019-02-27 at 11 40 32](https://user-images.githubusercontent.com/9733270/53484638-92882200-3a84-11e9-89db-995062705bb2.png)

**Comment by zdavatz** [comment]
Download for Refdata: https://dev.ywesee.com/Refdata/Wget

**Comment by zdavatz** [comment]
https://db.swisspeddose.ch/sign-in/

**Comment by zdavatz** [comment]
This is how we check in Ruby for the download Links containing dates: https://github.com/zdavatz/oddb.org/commit/a18fcba48e37e4ca512575f8158eb839aef64248

**Comment by zdavatz** [comment]
check this: https://github.com/pjq/wgetcookiedownload/blob/master/downloadswf.sh

**Comment by zdavatz** [comment]
https://github.com/zdavatz/aips2sqlite/blob/master/src/com/maxl/java/aips2sqlite/AllDown.java#L103

**Comment by zdavatz** [comment]
for complex Wget commands: https://addons.mozilla.org/en-US/firefox/addon/cliget/

**Comment by zdavatz** [comment]
Soure of cliget: https://github.com/zaidka/cliget
