### ISSUE TITLE
66547 Line is not broken properly

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#30]
<img width="1079" alt="bildschirmfoto 2019-03-01 um 16 15 02" src="https://user-images.githubusercontent.com/4953/53647197-4af8c600-3c3d-11e9-8554-1c9de97df77a.png">

**Comment by bettar** [comment]
The issue was caused by the boost xml parser, treating the tag `<br />` as a child, and therefore not using it as part to the parent text. The French xml data is structured differently from the German data.

**Comment by zdavatz** [comment]
good to know, thank you.

**Comment by zdavatz** [comment]
works.

**Comment by zdavatz** [comment]
should not be bold.

<img width="659" alt="bildschirmfoto 2019-03-05 um 13 32 53" src="https://user-images.githubusercontent.com/4953/53805708-3709d880-3f4b-11e9-9cb3-dd2664be78fd.png">
