### ISSUE TITLE
Title is missing in Description: 

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#35]
Title is missing in Description: 

<img width="1087" alt="bildschirmfoto 2019-03-01 um 19 08 04" src="https://user-images.githubusercontent.com/4953/53657166-ab93fd00-3c55-11e9-835f-6985851dcf5c.png">

This seems to happen for a special kind of XML.

**Comment by bettar** [comment]
All French titles in the XML "type 2" end with `<br />`. Some titles also contain `<br />` in the middle, for example RN 60024 `Amavita Gel pour le sport et<br />les rhumatismes rafraîchissant<br />`. How should they be handled ?

**Comment by zdavatz** [comment]
https://amiko.zurrose.ch/de/fi/gtin/60024

**Comment by zdavatz** [comment]
remove the BR and and replace it with a space.

**Comment by bettar** [comment]
This is how it works now: each title appears in two places, in an HTML page (middle pane of AmiKo) and as a chapter name (right pane of Amiko). For the HTML we can leave the `<br />` but for the chapter name it's replaced with a space.

**Comment by zdavatz** [comment]
Please remove the <br> in the Title as well.

**Comment by zdavatz** [comment]
this makes no sense:
<img width="1008" alt="bildschirmfoto 2019-03-05 um 09 42 29" src="https://user-images.githubusercontent.com/4953/53792022-0a45c900-3f2b-11e9-82b8-b4fed2d4ee36.png">
