### ISSUE TITLE
aips download fails

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#37]
```
wget --header "Host: download.swissmedicinfo.ch" --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" --header "Accept-Language: de,en-US;q=0.7,en;q=0.3" --referer "http://download.swissmedicinfo.ch/" --header "Content-Type: application/x-www-form-urlencoded" --header "Cookie: ASP.NET_SessionId=tewj5av5jeehd31fep3hmsyi; .ASPXAUTH=2514A8299808F4151CD9C70A484C9F06BDBD64CF72F97B29BA10263674AFC5A90ED5AA59CBB6000DCD631F80A887AC80BE0636DFDB37E7A3E802D2CE3B8F38486DF0833C9D6506F59AE1A2EB38059630E29565486A30A662E657ACAC01342D8A36A66F7F52BAE6B5AAAE071566EB9045786CBDA2610B3456C035190B68CF5EC6" --header "Upgrade-Insecure-Requests: 1" --method POST --body-data __VIEWSTATE=%2FwEPDwULLTE4MTg5MDc1ODUPZBYCZg9kFgICAw9kFgICCw8WAh4LXyFJdGVtQ291bnQCBBYIZg9kFgRmDxUBCD9MYW5nPURFZAIBDw8WCB4EVGV4dAUCREUeB1Rvb2xUaXAFAkRFHglGb250X0JvbGRnHgRfIVNCAoAQZGQCAg9kFgRmDxUBCD9MYW5nPUZSZAIBDw8WCB8BBQJGUh8CBQJGUh8DaB8EAoAQZGQCBA9kFgRmDxUBCD9MYW5nPUlUZAIBDw8WCB8BBQJJVB8CBQJJVB8DaB8EAoAQZGQCBg9kFgRmDxUBCD9MYW5nPUVOZAIBDw8WCB8BBQJFTh8CBQJFTh8DaB8EAoAQZGRkjlURDuFTfUSzCkU4Z%2FHgzJTwh8JAx9UG3UUmb1vpCvk%3D&__VIEWSTATEGENERATOR=CA0B0334&__EVENTVALIDATION=%2FwEdAAP75S3dOZ6sf0G6ruN2nzl0Ys46t3fbHVLzSTNxrdjIh8RrVmh3M0KCdbB64e6QzAIEClHNrqZ9LNHZdrtCdxbx9WpxB6%2BPdFanYBbOaZT3Pw%3D%3D&ctl00%24MainContent%24BtnYes=Ja "http://download.swissmedicinfo.ch/" --output-document "AipsDownload_20190305.zip"
```

**Comment by zdavatz** [comment]
https://askubuntu.com/questions/985966/how-to-download-a-file-from-a-website-that-prompts-a-popup-form

**Comment by zdavatz** [comment]
ctl00$MainContent$BtnYes

**Comment by zdavatz** [comment]
```
    def download_swissmedicinfo_xml(file = nil)
      return IO.read(file) if file
      setup_default_agent
      url  = "http://download.swissmedicinfo.ch/Accept.aspx?ReturnUrl=%2f"
      dir  = File.join(ODDB.config.data_dir, 'xml')
      FileUtils.mkdir_p dir
      name = 'swissmedicinfo'
      zip = File.join(dir, "#{name}.zip")
      response = nil
      if home = @agent.get(url)
        form = home.form_with(:id => 'Form1')
        bttn = form.button_with(:name => 'ctl00$MainContent$btnOK')
        if page = form.submit(bttn)
          form = page.form_with(:id => 'Form1')
          bttn = form.button_with(:name => 'ctl00$MainContent$BtnYes')
          response = form.submit(bttn)
        end
      end
```

**Comment by zdavatz** [comment]
https://github.com/zdavatz/oddb.org/blob/master/src/plugin/text_info.rb#L814

**Comment by zdavatz** [comment]
https://github.com/zaidka/cliget/blob/04ace6c1efc30ab8bb198624550f1ec7631937fd/wget.js

**Comment by zdavatz** [comment]
https://addons.mozilla.org/en-US/firefox/addon/cliget/

**Comment by bettar** [comment]
This gets the same cookie again
POST_DATA="ctl00%24MainContent%24BtnYes=Ja"
wget --post-data=$POST_DATA \
    --user-agent 'Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0' \
    --load-cookies=cookie.txt \
	"$URL" --save-cookies cookie2.txt --keep-session-cookies

**Comment by zdavatz** [comment]
`wget --post-data=ctl00%24MainContent%24BtnYes=Ja --user-agent 'Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0' --load-cookies=cookie.txt "http://download.swissmedicinfo.ch/Accept.aspx?ReturnUrl=%2f" --save-cookies cookie2.txt --keep-session-cookies`

**Comment by zdavatz** [comment]
```
curl --header "Host: download.swissmedicinfo.ch" --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" --header "Accept-Language: de,en-US;q=0.7,en;q=0.3" --referer "http://download.swissmedicinfo.ch/" --header "Content-Type: application/x-www-form-urlencoded" --cookie "ASP.NET_SessionId=pdulaal0cpye0ao4vub121hz; .ASPXAUTH=4632FE21417CAEFEC23EC06811FFA4CA45A8D288E3B50B402B29B42CDA95B9335EA997E6C22198ACE1092D599D707855C552C4591CE61D537AAFC2F738E4B1A413A8E1EE3A693A86291308180BD2BEF3F3DB13BDDF2F800B3720EEF0470674CD6D8A99301053BB9FEB5E8E974A589A2D2C44155F09B3A83FED94E65BAA231D93" --header "Upgrade-Insecure-Requests: 1" --request POST --data-urlencode "__VIEWSTATE=/wEPDwULLTE4MTg5MDc1ODUPZBYCZg9kFgICAw9kFgICCw8WAh4LXyFJdGVtQ291bnQCBBYIZg9kFgRmDxUBCD9MYW5nPURFZAIBDw8WCB4EVGV4dAUCREUeB1Rvb2xUaXAFAkRFHglGb250X0JvbGRnHgRfIVNCAoAQZGQCAg9kFgRmDxUBCD9MYW5nPUZSZAIBDw8WCB8BBQJGUh8CBQJGUh8DaB8EAoAQZGQCBA9kFgRmDxUBCD9MYW5nPUlUZAIBDw8WCB8BBQJJVB8CBQJJVB8DaB8EAoAQZGQCBg9kFgRmDxUBCD9MYW5nPUVOZAIBDw8WCB8BBQJFTh8CBQJFTh8DaB8EAoAQZGRkjlURDuFTfUSzCkU4Z/HgzJTwh8JAx9UG3UUmb1vpCvk=" --data-urlencode "__VIEWSTATEGENERATOR=CA0B0334" --data-urlencode "__EVENTVALIDATION=/wEdAAP75S3dOZ6sf0G6ruN2nzl0Ys46t3fbHVLzSTNxrdjIh8RrVmh3M0KCdbB64e6QzAIEClHNrqZ9LNHZdrtCdxbx9WpxB6+PdFanYBbOaZT3Pw==" --data-urlencode "ctl00%24MainContent%24BtnYes=Ja" "http://download.swissmedicinfo.ch/" --output "AipsDownload_20190305.zip"
```

**Comment by zdavatz** [comment]
wget --header "Host: download.swissmedicinfo.ch" --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" --header "Accept-Language: de,en-US;q=0.7,en;q=0.3" --referer "http://download.swissmedicinfo.ch/" --header "Content-Type: application/x-www-form-urlencoded" --header "Cookie: ASP.NET_SessionId=pdulaal0cpye0ao4vub121hz; .ASPXAUTH=4632FE21417CAEFEC23EC06811FFA4CA45A8D288E3B50B402B29B42CDA95B9335EA997E6C22198ACE1092D599D707855C552C4591CE61D537AAFC2F738E4B1A413A8E1EE3A693A86291308180BD2BEF3F3DB13BDDF2F800B3720EEF0470674CD6D8A99301053BB9FEB5E8E974A589A2D2C44155F09B3A83FED94E65BAA231D93" --header "Upgrade-Insecure-Requests: 1" --method POST --body-data __VIEWSTATE=%2FwEPDwULLTE4MTg5MDc1ODUPZBYCZg9kFgICAw9kFgICCw8WAh4LXyFJdGVtQ291bnQCBBYIZg9kFgRmDxUBCD9MYW5nPURFZAIBDw8WCB4EVGV4dAUCREUeB1Rvb2xUaXAFAkRFHglGb250X0JvbGRnHgRfIVNCAoAQZGQCAg9kFgRmDxUBCD9MYW5nPUZSZAIBDw8WCB8BBQJGUh8CBQJGUh8DaB8EAoAQZGQCBA9kFgRmDxUBCD9MYW5nPUlUZAIBDw8WCB8BBQJJVB8CBQJJVB8DaB8EAoAQZGQCBg9kFgRmDxUBCD9MYW5nPUVOZAIBDw8WCB8BBQJFTh8CBQJFTh8DaB8EAoAQZGRkjlURDuFTfUSzCkU4Z%2FHgzJTwh8JAx9UG3UUmb1vpCvk%3D&__VIEWSTATEGENERATOR=CA0B0334&__EVENTVALIDATION=%2FwEdAAP75S3dOZ6sf0G6ruN2nzl0Ys46t3fbHVLzSTNxrdjIh8RrVmh3M0KCdbB64e6QzAIEClHNrqZ9LNHZdrtCdxbx9WpxB6%2BPdFanYBbOaZT3Pw%3D%3D&ctl00%24MainContent%24BtnYes=Ja "http://download.swissmedicinfo.ch/" --output-document "AipsDownload_20190305.zip"

**Comment by zdavatz** [comment]
Why does the Cookie File say false? `download.swissmedicinfo.ch      FALSE   /       FALSE   0       ASP.NET_SessionId       45rweoiuxpacdcglnvyb53ou`

**Comment by bettar** [comment]
removing the user agent in the first wget still gets the same cookie with FALSE

**Comment by zdavatz** [comment]
I think we need TRUE as return value.

**Comment by bettar** [comment]
Now I can get both cookies, and both have FALSE in them, and the download works, so it looks like this is not so important, even not knowing what the FALSE refers to.
