### ISSUE TITLE
br Tag with to many square brackets for 47033, 48447, 24714

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#39]
<img width="221" alt="bildschirmfoto 2019-03-06 um 09 40 32" src="https://user-images.githubusercontent.com/4953/53867371-fd40dc80-3ff3-11e9-9653-32ce9e1135b8.png">
<img width="423" alt="bildschirmfoto 2019-03-06 um 09 40 38" src="https://user-images.githubusercontent.com/4953/53867372-fdd97300-3ff3-11e9-8bf2-9b421081ac01.png">

**Comment by bettar** [comment]
![screenshot 2019-03-06 at 10 27 34](https://user-images.githubusercontent.com/9733270/53870436-865b1200-3ffa-11e9-9a55-c0604ded963c.png)

**Comment by bettar** [comment]
I can confirm that since commit 09109bc I cannot reproduce the problem

**Comment by zdavatz** [comment]
my File size is: 275308544

**Comment by bettar** [comment]
I think you are not running the cpp2sqlite that you build, but the one that you installed sometime in the past. I suggest we should add a version number to the footer `Auto-generated by cpp2sqlite v1.2.456 on Wed Mar 6 11:15:03 2019`

**Comment by zdavatz** [comment]
working with 307f41567709153024d61fbe9ebb
