### ISSUE TITLE
Full-Text-Search for swisspeddose only finds 10 results

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#42]
1. Open AmiKo macOS
2. Update data with "Apple+A"
3. Click _Voll-Text-Suche_
4. Search for swisspeddose
5. Only 10 results are found. There should be more.

**Comment by bettar** [comment]
It's probably worth mentioning that this search is done on the file `amiko_frequency_de.db` generated with a Python script.
