### ISSUE TITLE
Anchor jump to swisspeddose chapter does not work

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#43]
1. Open AmiKo macOS
2. Update data with "Apple+A"
3. Click _Voll-Text-Suche_
4. Search for swisspeddose
5. Click _Swisspeddose_ below _Nerifene_
6. It does not jump to the section.

**Comment by bettar** [comment]
This is likely to be more relevant as an issue for https://github.com/zdavatz/fachinfo_ai
