### ISSUE TITLE
Update Interactions File

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#46]
Input: http://download.epha.ch/data/matrix/matrix.csv
Output DE: http://pillbox.oddb.org/drug_interactions_csv_de.zip
Output FR: http://pillbox.oddb.org/drug_interactions_csv_fr.zip

**Comment by zdavatz** [comment]
See Ponstan and Marcoumar as an example: https://amiko.oddb.org/interactions/7680193950141,7680307850299

**Comment by zdavatz** [comment]
Also create and XLIFF file for POedit to translate.

**Comment by zdavatz** [comment]
https://www.deepl.com/de/api.html

**Comment by bettar** [comment]
Some statistics: matrix.csv has 15913 lines, each with 3 sentences to be translated. Of the total 47739 sentences, only 2856 are "unique"

**Comment by bettar** [comment]
I noticed that is a sentence contains some code, for example `Acenocoumarol wird u.a. über CYP2C9 metabolisiert.` then DeepL translation fails

**Comment by zdavatz** [comment]
`Acenocoumarol wird u.a. über CYP2C9 metabolisiert.` -> `L'acénocoumarol est métabolisé par le CYP2C9.`

**Comment by bettar** [comment]
2 Terbinafin hemmt CYP2D6  und damit auch den Metabolismus von Tramadol .

**Comment by zdavatz** [comment]
translates to: `La terbinafine inhibe le CYP2D6 et donc aussi le métabolisme du tramadol.`

**Comment by zdavatz** [comment]
~/.software/cpp2sqlite/scripts>`./deepl.sh ../build/deepl.in.txt`

**Comment by zdavatz** [comment]
[translated-FR.txt](https://github.com/zdavatz/cpp2sqlite/files/2953336/translated-FR.txt)
[not-translated-FR.txt](https://github.com/zdavatz/cpp2sqlite/files/2953337/not-translated-FR.txt)

**Comment by zdavatz** [comment]
[not-translated-FR-libre.txt](https://github.com/zdavatz/cpp2sqlite/files/2953490/not-translated-FR-libre.txt)

**Comment by zdavatz** [comment]
[not-translated-FR-104.txt](https://github.com/zdavatz/cpp2sqlite/files/2953844/not-translated-FR-104.txt) (104) lines.

**Comment by zdavatz** [comment]
Risikoklasse -> Catégorie de risque
Möglicher Effekt -> Effet possible
Mechanismus -> Mécanisme
Empfohlene Massnahmen -> Mesures recommandées   
Keine Massnahmen notwendig -> Aucune mesure n'est nécessaire
Vorsichtsmassnahmen empfohlen -> Précautions recommandées
Regelmässige Überwachung -> Suivi régulier
Kombination vermeiden -> Éviter la combinaison
Kontraindiziert -> Contre-indiqué

**Comment by zdavatz** [comment]
Line 1095 of DeepL.in.txt `Eine Dosisanpassung ist gemäss Fachinformation nicht nötig. Dabigatran sollte zur Vermeidung der Interaktion 2 Stunden vor Verapamil gegeben werden. Darunter stieg die Cmax um weniger als 20% an. Vermehrte Aufmerksamkeit sollte auf Anzeichen von Blutungen gerichtet werden. Eine Ãberwachung der Gerinnungsparameter kann nötig sein.` gets translated by Deepl with an extra line break between  `20%`, and the annotation.

**Comment by zdavatz** [comment]
Use the FR translations from https://github.com/zdavatz/cpp2sqlite/blob/master/input/atc_codes_multi_lingual.txt

**Comment by zdavatz** [comment]
Line 1603 also gets an extra newline, from `Fluvoxamin hemmt CYP1A2 stark, über welches Agomelatin zu 90% abgebaut wird. Dies führt zu eröhten Agomelatin-Plasmakonzentrationen.` to `La fluvoxamine inhibe fortement le CYP1A2, par lequel l'agomélatine peut être convertie en 90
est construit. Il en résulte une augmentation des concentrations plasmatiques d'agomélatine.`

**Comment by zdavatz** [comment]
![](https://i.imgur.com/lUYozFN.png)
