### ISSUE TITLE
strange characters

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#49]
<img width="594" alt="Bildschirmfoto 2019-03-19 um 17 16 38" src="https://user-images.githubusercontent.com/4953/54623029-00fc4680-4a6b-11e9-9db2-af89e6414b25.png">

<img width="437" alt="Bildschirmfoto 2019-03-19 um 17 17 58" src="https://user-images.githubusercontent.com/4953/54623128-3acd4d00-4a6b-11e9-959b-fa96a89194e3.png">

**Comment by bettar** [comment]
To put things into perspective, this also applies to the db file created with Java:
![Screenshot 2019-03-19 at 18 07 32](https://user-images.githubusercontent.com/9733270/54626730-0f019580-4a72-11e9-8c28-674efc50fb6b.png)
