### ISSUE TITLE
Sappinfo Link not working

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#52]
1. Import DB to AmiKo macOS.
2. Click on the link. Nothing happens.

<img width="751" alt="Screenshot 2019-05-01 at 01 23 47" src="https://user-images.githubusercontent.com/4953/56999679-7f8eec80-6bb0-11e9-828f-fdd791eed832.png">

**Comment by alex-be** [comment]
For 74% of the ATCs the URL is the word "nein". Now that we know it could happen, we can fix it.
