### ISSUE TITLE
Sappinfo: Only generate the field if the XLSX field of the column contains useful information.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#53]
<img width="756" alt="Screenshot 2019-05-01 at 01 20 31" src="https://user-images.githubusercontent.com/4953/56999780-ead8be80-6bb0-11e9-962e-5a6f12f9c4e1.png">

**Comment by bettar** [comment]
For the table column "Dose adjustment" (Dosisanpassung) Issue #51 shows it should be there. The ??? are a temporary placeholder for the corresponding text that at present cannot be found in the XLXS file. Please update  issue #51 which is regarded as "the specifications" for this functionality and make it clear where to get the Dosisanpassung information from.

**Comment by bettar** [comment]
About the other empty columns, they are temporarily there because they are empty for ALL the ATCs. They are a temporary reminder for you to specify where to get that information in the XLXS file. Again, please update the "specifications" in issue #51.

**Comment by zdavatz** [comment]
#51 is closed. At the time when I created the issue the input file obviously hat some different column names. 

Just use the _new_ column headers as table names.

**Comment by zdavatz** [comment]
Table headers for Stillzeit:
Hauptindikation | Indikation | Wirkstoff | Applikationsart | max. verabreichte Tagesdosis | Bemerkungen zur Dosierung | Zulassungsnummer | ATC | SAPP-Monographie | 

Table headers for Schwangerschaft:
Hauptindikation | Indikation | Wirkstoff | Applikationsart | max. verabreichte Tagesdosis 1. Trimenon | max. verabreichte Tagesdosis 2. Trimenon | max. verabreichte Tagesdosis 3. Trimenon | Bemerkungen zur Dosierung | Peripartale Dosierung | Bemerkungen zur peripartalen Dosierung | Zulassungsnummer | ATC | SAPP-Monographie | 

Only generate the field if the XLSX field of the column contains useful information.

Issue 51 was sample data based on any old Input file.

**Comment by zdavatz** [comment]
Also see #54

**Comment by bettar** [comment]
Some columns have no name but information. I don't have a definition of "useful" to decide whether they should be used. One example: table Stillzeit column T

Sheet title: Stillzeit
0	<Klinik>
1	<Hauptindikation>
2	<Indikation>
3	<Wirkstoffklasse>
4	<ATC Level1>
5	<Wirstoffklasse>
6	<Wirkstoff>
7	<Applikationsart>
8	<max. verabreichte Tagesdosis>
9	<Bemerkungen zur Dosierung>
10	<USZ>
11	<>
12	<>
13	<>
14	<>
15	<SAPP>
16	<Zulassungsnummer>
17	<ATC>
18	<SAPP-Monographie>
19	<>
20	<Filter>

Sheet title: Schwangerschaft
0	<Klinik>
1	<Hauptindikation>
2	<Indikation>
3	<Wirstoffklasse nur einmal>
4	<ATC Level 1>
5	<Wirkstoffklasse>
6	<Wirkstoff>
7	<Applikationsart>
8	<max. verabreichte Tagesdosis 1. Trimenon>
9	<max. verabreichte Tagesdosis 2. Trimenon>
10	<max. verabreichte Tagesdosis 3. Trimenon>
11	<Bemerkungen zur Dosierung>
12	<Peripartale Dosierung>
13	<Bemerkungen zur peripartalen Dosierung>
14	<USZ>
15	<USZ>
16	<>
17	<>
18	<>
19	<>
20	<SAPP 1.>
21	<SAPP 2.>
22	<SAPP 3.>
23	<>
24	<Zulassungsnummer>
25	<ATC>
26	<SAPP-Monographie>
27	<>
28	<Filter>
29	<>

**Comment by bettar** [comment]
Another example: sheet Schwangerschaft column A "Klinik", is that "useful" or not ?

**Comment by bettar** [comment]
Most importantly, it is not clear which information you want in the text before the table, and which one should go in the actual table.

**Comment by zdavatz** [comment]
Schwangerschaft: B, C, G, H, I, J, K, L, M, N, Z, AA
Stillzeit: B, C, G, H, I, J, Q, S

**Comment by bettar** [comment]
Please confirm that you want the following columns before the table, abds the remaining columns inside the table:
```
Stillzeit:
R ATC-Codes
G Wirkstoff
B Hauptindikation
C Indikation

Schwangerschaft:
Z ATC-Codes
G Wirkstoff
B Hauptindikation
C Indikation
AA SAPP-Monographie
```
