### ISSUE TITLE
Dosisanpassung -> Bemerkungen zur Dosierung

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#54]
For ATC Code _P03AX03_ the table is missing _Bemerkungen zur Dosierung_ and its information contained in the cell: _keine Langzeitanwendung_

Please make sure to use all column headers of both sheets _Schwangerschaft_ and _Stillzeit_.

For the last two columns the information does not have to be written out.

**Comment by bettar** [comment]
"Bemerkungen zur peripartalen Dosierung" is column N.
The text _keine Langzeitanwendung_ appeared in column L

**Comment by zdavatz** [comment]
Use the column if it contains information in the field. Otherwise do not use the column.

**Comment by zdavatz** [comment]
AFAICT the new name for _Dosisanpassung_ is now _Bemerkungen zur Dosierung_. There is no more column _Dosisanpassung_ in the XLSX.
