### ISSUE TITLE
Sappinfo: missing Bemerkungen zur peripartalen Dosierung

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#55]
For ATC Code G02AD06 the column _Bemerkungen zur peripartalen Dosierung_ is still missing in the output table. Also see #54

**Comment by zdavatz** [comment]
The missing text is: _je nach Gestationsalter_

**Comment by zdavatz** [comment]
<img width="747" alt="Screenshot 2019-05-01 at 01 47 43" src="https://user-images.githubusercontent.com/4953/57000406-b6b2cd00-6bb3-11e9-897c-ed7ceb2534c6.png">

**Comment by bettar** [comment]
Yes, it needs to be fixed. It's happening because its ATC column has more than one ATC code.

**Comment by bettar** [comment]
![Screenshot 2019-05-01 at 10 26 12](https://user-images.githubusercontent.com/9733270/57010228-f4d3df00-6bfb-11e9-8614-fa33d006f525.png)
