### ISSUE TITLE
ATC A02BB01 missing table completely.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#57]
For ATC code A02BB01 on line 734, sheet Schwangerschaft there is nothing created at all yet. Seems like only the first ATC-Code is being parsed but not the second one.

**Comment by zdavatz** [comment]
Seems like only the first ATC-Code is being parsed.

**Comment by bettar** [comment]
Acknowledged. It needs to be fixed. Sometimes there are two ATC codes in the ATC column, and right now NEITHER of them is used. Do you want them to stay "paired" in the text preceding each table, for example in the case do you want to see
ATC-Code: A02BB01
or
ATC-Code: G02AD06, A02BB01

**Comment by zdavatz** [comment]
ATC-Code: G02AD06, A02BB01 looks good.
