### ISSUE TITLE
Default Sort sqlite so Fachinfo Names starting with numbers come last.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#6]
In the Java-DB these go last, not first:

<img width="377" alt="bildschirmfoto 2019-02-15 um 22 10 20" src="https://user-images.githubusercontent.com/4953/52884517-7f18b500-316e-11e9-830f-b240ca661bbb.png">

**Comment by bettar** [comment]
I think it's up to the application doing the DB query and showing the results to define any particular sorting order

**Comment by bettar** [comment]
Just for reference the java project does this reordering in file SqlDatabase.java, line 446, function `reorderAlphaDB`
