### ISSUE TITLE
French Data is empty

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#62]
Why is the French Data empty?

https://amiko.oddb.org/fr/fi?gtin=63001&highlight=Sappinfo&anchor=Section9052

**Comment by bettar** [comment]
For me it's "kind of" empty. Also, I don't get the swisspeddose.

![Screenshot 2019-05-06 at 09 20 21](https://user-images.githubusercontent.com/9733270/57211335-3390dd00-6fe0-11e9-87c6-4be86476eaee.png)

**Comment by bettar** [comment]
The German version says "keine Angaben"

**Comment by zdavatz** [comment]
When did you last update?

**Comment by bettar** [comment]
30 minutes ago :-) I am rechecking now with the latest...

**Comment by bettar** [comment]
With the latest downloads the swisspeddose is there, so that is okay.

**Comment by zdavatz** [comment]
I do
```
rm -f /usr/local/src/cpp2sqlite/output/amiko_update_done
cd /usr/local/src/cpp2sqlite/scripts; ./download.sh
cd /usr/local/src/cpp2sqlite/build
time ./cpp2sqlite --verbose --lang=fr --inDir ../input
time ./cpp2sqlite --verbose --inDir ../input
/bin/bash /usr/local/src/scp_amiko_cpp_dbs_to_panda
```

**Comment by zdavatz** [comment]
http://pillbox.oddb.org/amiko_report_fr.html
