### ISSUE TITLE
Why is this not capital anymore?

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#66]
<img width="444" alt="Screenshot 2019-05-06 at 11 45 27" src="https://user-images.githubusercontent.com/4953/57218027-942a1500-6ff4-11e9-9949-e6ea034f373d.png">

**Comment by bettar** [comment]
because it comes after a colon. it would be bad grammar, but you can easily modify it to your taste in sapping.cpp lines 113-152

**Comment by zdavatz** [comment]
corrected: 616d63a16a29c716c42ea3b71c7cf17027a8c75a
