### ISSUE TITLE
m&sup2 HTML character not yet recognized.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#7]
`m&sup2` not yet recognized in Reg# _66022_

<img width="243" alt="bildschirmfoto 2019-02-17 um 10 01 58" src="https://user-images.githubusercontent.com/4953/52910669-2abf2380-329b-11e9-9dbf-7d2734d0da6b.png">

Please start paying attention to all special HTML characters.

Also see: http://turner.faculty.swau.edu/webstuff/htmlsymbols.html

**Comment by zdavatz** [comment]
and more special HTML characters.
<img width="272" alt="bildschirmfoto 2019-02-17 um 10 13 33" src="https://user-images.githubusercontent.com/4953/52910788-d61ca800-329c-11e9-9657-17190983ba1e.png">

we need to catch them all.

**Comment by zdavatz** [comment]
Also see: https://stackoverflow.com/questions/5665231/most-efficient-way-to-escape-xml-html-in-c-string

**Comment by zdavatz** [comment]
<img width="986" alt="bildschirmfoto 2019-02-17 um 17 24 34" src="https://user-images.githubusercontent.com/4953/52915842-f9fddf00-32d8-11e9-92a4-63a220ad0d0f.png">

**Comment by bettar** [comment]
About this issue title, the HTML symbols start with `&` not with `m&`

**Comment by bettar** [comment]
The link you are suggesting for reference doesn't contain `&sup2;`

**Comment by bettar** [comment]
The second link you provide for reference is talking about the opposite conversion, from special characters to HTML encoded symbols

**Comment by bettar** [comment]
There is more to it than just converting (or skip converting in some cases) special characters to HTML symbols. Fort example for Beromun rn 54745 the symbol `&Ograve;` would get converted to `Ò` but instead the Java code show a conversion to `®` and later it gets completely dropped off.

**Comment by bettar** [comment]
IMHO there is something fundamentally wrong with this idea of replacing valid HTML symbols in the HTML code with their equivalent UTF8 characters.

**Comment by bettar** [comment]
I confirmed that the problem is in the source XML code from AIPS, because it contains the wrong string `&sup2;` instead of `&sup;2`

**Comment by zdavatz** [comment]
<img width="715" alt="bildschirmfoto 2019-02-18 um 17 26 17" src="https://user-images.githubusercontent.com/4953/52964362-67c20d80-33a2-11e9-9456-1ee8cd53c429.png">

**Comment by bettar** [comment]
![screenshot 2019-02-18 at 17 32 10](https://user-images.githubusercontent.com/9733270/52964665-28e08780-33a3-11e9-9f59-bc3cbcc2eedd.png)

**Comment by zdavatz** [comment]
much better.

**Comment by zdavatz** [comment]
53985
