### ISSUE TITLE
Pregnancy/Breastfeeding stats

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#70]
Please explain these stats:

```
with <breastFeed>: 703
without <breastFeed>: 265
with <pregnancy>: 921
without <pregnancy>: 47
```

**Comment by bettar** [comment]
703 + 265 = 968
921 + 47 = 968

The 968 is the ATCs from the AIPS file. For each one of them there is a matching breastfeed in Sappinfo or not, and there is a matching pregnancy in Sappinfo or not.

**Comment by zdavatz** [comment]
Thank you!

**Comment by zdavatz** [comment]
Something is wrong with the numbers. There are only 226 unique ATC-Codes in all of [sappinfo.xlsx](https://github.com/zdavatz/cpp2sqlite/blob/master/input/sappinfo.xlsx) according to the [Report](http://pillbox.oddb.org/amiko_report_de.html)

**Comment by bettar** [comment]
I confirmed the stats for Sappinfo Usage:
Unique ATC used: 226
ATC used again: 967 times

**Comment by zdavatz** [comment]
SappInfo

ATC Sappinfo usage

Unique ATC pregnancy: 120
Unique ATC breastfeeding: 45

Breastfeeding tables created: 1059
Pregnancy tables created: 1954

**Comment by bettar** [comment]
ATC codes 4323
• from aips: 4268
• from swissmedic: 43
• unique (from both aips and swissmedic): 1693

**Comment by bettar** [comment]
Sappinfo unique ATC
- breastFeed: 145
- pregnancy: 202
Sappinfo tables created
- breastFeed: 1058
- pregnancy: 1953

**Comment by zdavatz** [comment]
👍
