### ISSUE TITLE
floating point dosage missmatch

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#74]
~Check if there is a space after the `e`.~

![4e](https://user-images.githubusercontent.com/4953/57769629-af8cd280-770e-11e9-8a71-aa265a4777ca.jpg)

**Comment by zdavatz** [comment]
Check if there is a space after the `e`.

**Comment by zdavatz** [comment]
![5mg](https://user-images.githubusercontent.com/4953/57769781-0a262e80-770f-11e9-8b5c-5a202a7f40d9.jpg)

**Comment by zdavatz** [comment]
`0.05` gets skipped.

![zero_dot](https://user-images.githubusercontent.com/4953/57769949-6d17c580-770f-11e9-8436-5eb5b0106386.jpg)

**Comment by bettar** [comment]
Floating point numbers are not parsed yet

**Comment by bettar** [comment]
Simply checking for a space after g fixes 7680450370293 but breaks 7680207130118.
