### ISSUE TITLE
Links do not point to the correct SAPP Monographie

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#84]
<img width="731" alt="Screenshot 2019-05-21 at 16 46 34" src="https://user-images.githubusercontent.com/4953/58106393-562e1300-7be8-11e9-8b15-c8c54d6be53e.png">

The first link points to `https://www.<span%20class=` which is obviously wrong.

**Comment by bettar** [comment]
I checked by copy pasting the HTML code from the DB file and saving it as an HTML file on my local disc, then opening in Safari the link seems to be fine. This is of course with the DB file that I generate.

**Comment by zdavatz** [comment]
Why is the problem only happening on Windows and macOS?

**Comment by zdavatz** [comment]
Now it works again!
