### ISSUE TITLE
pharma.csv has no output in ddd and ddd_calculation

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#87]
pharma.csv has no output in `ddd` and `ddd_calculation`

**Comment by zdavatz** [comment]
I use the following command:

`./pharma --inDir ../downloads/`

**Comment by bettar** [comment]
It should be
`./pharma --inDir ../input`

**Comment by zdavatz** [comment]
What about `workDir`

**Comment by bettar** [comment]
The work dir is used for development to have flexibility in defining a different parent for the download and output directories. Normally is never used because it defaults to the same as the parent of the input directory

**Comment by zdavatz** [comment]
very cool, thank you!
