### ISSUE TITLE
Alcacyl Fachinfo is empty

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#9]
<img width="1096" alt="bildschirmfoto 2019-02-17 um 17 29 05" src="https://user-images.githubusercontent.com/4953/52915890-9c1dc700-32d9-11e9-90da-eadd042c75cd.png">

**Comment by bettar** [comment]
Interesting. The source XML code has section numbers starting at 7000 with increments of 50...

and it doesn't look like any other XML, so parsing fails. Are we sure that the source data is not corrupted ?

**Comment by zdavatz** [comment]
it is not. See the Java DB. We can not miss any Fachinfos.

**Comment by bettar** [comment]
Also rn 53563 Wellvone

**Comment by bettar** [comment]
A little insight into the issue: there are three types of xml in the AIPS file:

225 are multiline, starting with `<div id="monographie"><div class="MonTitle">`

9 are a single long line, starting with `<div id="Monographie"><div class="Title">`

4070 are a single long line, starting with `<?xml version="1.0" encoding="utf-8"?>`

**Comment by zdavatz** [comment]
very good to know!

**Comment by zdavatz** [comment]
The _9_ have no ATC-Code an no Reg#
