### ISSUE TITLE
Enhance pharma.csv with FI storage information with flag --storage

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#91]
1. Enhance Pharma.csv with information from the chapter _Sonstige Hinweise_  **after** subchapter _Besondere Lagerungshinweise_. Grab all Text upto next chapter _Zulassungsnummer_. Put the text into an additional column in pharma.csv
2. Use `./pharma --storage` to generate the additional information in `pharma.csv`.

**Comment by zdavatz** [comment]
Scentence extraction from Fachinfo has already been done in macOS, this may help: https://github.com/zdavatz/amiko-osx/issues/44

**Comment by bettar** [comment]
What's the new column's header, "storage" ?

**Comment by zdavatz** [comment]
This seems to work in the `build` dir: 
`./pharma --inDir ../downloads/ --storage`
