### ISSUE TITLE
extract storage information from AUS API

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#92]
see #90 

1. See [API documentation](https://github.com/zdavatz/cpp2sqlite/files/3247311/Public.ARTG.Search.Web.Service.docx)
2. Access AUS API with i.e. Curl: `curl -s "https://www.tga.gov.au/ARTGSearch/ARTGWebService.svc/JSON/ARTGValueSearch/?pagestart=1&pageend=1000" | jq . > au1`
Make sure to download all records. Above command will only downlaod the first 1000 records. See API Documentation, last page.
3. Write a CSV file for the following Tags: _ARTG Id_, _Entry Type_, _Product Type_, _Name_, _Sponsor_, _Date Approved_, _Ingredients_, _Class_, _Poison_, _Temperature_
4. Use `./pharma_aus` to create the file `pharma_aus.csv`.
5. Delimiter is ";".

As a sample compare these products between Australia and CH:
- Entresto
- Humira
- Mavenclad
- Xarelto
- Remicade

If the Brandname matches then check for differences in Temperature according to Galenic Form/Dosage/Package size.

**Comment by pgee70** [comment]
the url will now be `http://data.tga.gov.au/ARTGSearch/ARTGWebService.svc/JSON/ARTGValueSearch/?pagestart=1&pageend=1000`
