### ISSUE TITLE
Xarelto and Remicade have no Temperature information in pharma.csv

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#95]
Lets start looking for the scentences that contain `°C` and add only them if there are any in the chapter `Besondere Lagerungshinweise`.

Test with: `./pharma --storage`

Products for testing:
~- Entresto~
~- Humira~
~- Mavenclad~
~- Xarelto~
- Remicade

**Comment by bettar** [comment]
I cannot reproduce the problem with Entresto. The temperature information seems to be there, as described in Issue #91 
![95](https://user-images.githubusercontent.com/9733270/59344260-0259aa00-8d0e-11e9-9b06-24122b9c14b7.png)

**Comment by bettar** [comment]
Same for Xarelto, no problem here:
![95-xarelto](https://user-images.githubusercontent.com/9733270/59344558-a2173800-8d0e-11e9-956a-0e6f69740fa1.png)

**Comment by zdavatz** [comment]
I agree. I did not find it with Grepping `grep -r XARELTO /home/zeno/.software/cpp2sqlite/output/pharma.csv`

**Comment by bettar** [comment]
Also no problem:
![95-remicade](https://user-images.githubusercontent.com/9733270/59364054-89bb1380-8d36-11e9-8481-396a5372de13.png)

**Comment by zdavatz** [comment]
Ok, great! Again my Grep mistake! Sorry about that!
